### ISSUE TITLE
Fail to build on FreeBSD 14.3-RELEASE-p3

### ISSUE THREAD

**Issue by avysk** [Julien-cpsn/desktop-tui#10]
`cargo install` =>
```
error[E0308]: mismatched types
   --> /home/alexey/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.22.3/src/sys/event.rs:226:19
    |
226 |             data: data as type_of_data,
    |                   ^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `isize`

error[E0063]: missing field `ext` in initializer of `kevent`
   --> /home/alexey/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.22.3/src/sys/event.rs:221:26
    |
221 |         KEvent { kevent: libc::kevent {
    |                          ^^^^^^^^^^^^ missing `ext`

Some errors have detailed explanations: E0063, E0308.
For more information about an error, try `rustc --explain E0063`.
error: could not compile `nix` (lib) due to 2 previous errors
```

Another error with `--locked`:
```
error[E0599]: no associated item named `IUTF8` found for struct `InputModes` in the current scope
   --> /home/alexey/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/virtual-terminal-0.1.4/src/lib.rs:195:51
    |
195 |                 .set(rustix::termios::InputModes::IUTF8, true);
    |                                                   ^^^^^ associated item not found in `InputModes`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `virtual-terminal` (lib) due to 1 previous error
```
